---
- name: Install git
  ansible.builtin.apt:
    pkg:
      - git

- name: Copy clockwork code from git
  ansible.builtin.git:
    repo: '{{ clockwork_repo }}'
    dest: '{{ clockwork_install_path }}'
    version: '{{ clockwork_checkout_commit }}'
    accept_newhostkey: yes
