---
- name: Converge
  hosts: all
  vars:
    clockwork_git_deploy_key: "<fill in>"
    clockwork_secret_key: "super_secret"
    clockwork_google_client_id: ""
    clockwork_google_client_secret: ""
    clockwork_ssh_private_key: "clockwork-ssh-private-key"
    clockwork_clusters:
      - name: cluster1
        account_field: cluster1_username
        update_field: false
        allocations: "*"
        timezone: America/Montreal
        fetch_remote: false
      - name: cluster2
        account_field: cluster2_username
        update_field: cluster2_update_key
        allocations: [ def-cluster-alloc ]
        timezone: America/Vancouver
        fetch_remote: true
        remote_user: automation
        remote_hostname: cluster2.example.com
        remote_path: /lustre/reports/slurm
        remote_interval: 30
  tasks:
    - name: Setup MongoDB
      include_role:
        name: mila.clockwork
        tasks_from: setup_mongod
    - name: Setup clockwork server
      include_role:
        name: mila.clockwork
        tasks_from: setup_server
    - name: Setup clockwork scrape
      include_role:
        name: mila.clockwork
        tasks_from: setup_scrape
    - name: Setup clockwork clusterstats cron
      include_role:
        name: mila.clockwork
        tasks_from: setup_clusterstats_cron
